version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=khamla
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: yarn dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=khamla
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
