version: "3"
services:
  node-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=8000
    # env_file:
    #     - ./.env
